bin/git-gen: fix some gen boilerplate way
Signed-off-by: Koichi Shiraishi <zchee.io@gmail.com>

diff --git a/bin/git-gen b/bin/git-gen
--- a/bin/git-gen
+++ b/bin/git-gen
@@ -1,19 +1,22 @@
 #!/usr/bin/env bash
 set -euo pipefail
-IFS=$'\n\t'
 
 # ----------------------------------------------------------------------------
 # Initialize the git repository
 
 info() { printf "\\x1b[1;34m[INFO]\\x1b[0m %s\\n" "$1"; }
 warn() { printf "\\x1b[1;33m[WARN]\\x1b[0m %s\\n" "$1"; }
-fatal() { printf "\x1b[1;34m[FATAL]\x1b[0m %s\\n" "$1"; exit 1; }
+error() {
+  printf "\x1b[1;34m[ERROR]\x1b[0m %s\\n" "$1"
+  exit 1
+}
 
 usage() {
   printf "Usage: %s [license] [language...]" "$(basename "$0")"
   exit 1
 }
 
+declare GIIGNORE_REPOSITORY
 GIIGNORE_REPOSITORY="$HOME/src/github.com/github/gitignore"
 
 # fetch latest gitignore
@@ -29,14 +32,15 @@ if [[ "$#" -lt 2 ]]; then
   usage
 fi
 
-ARG_LICENSE="$1"; shift
+ARG_LICENSE="$1"
+shift
 ARG_LANGUAGES="$*"
 ORGANIZATION_NAME="$(basename "$(dirname "$PWD")")"
 PROJECT_NAME="${PROJECT_NAME:-$(basename "$PWD")}"
 
-
+declare LICENSE_TYPE
 case "$ARG_LICENSE" in
-  bsd|bsd-project)
+  bsd | bsd-project)
     LICENSE_TYPE=BSD3_PROJECT
     ;;
   bsd-owner)
@@ -45,16 +49,16 @@ case "$ARG_LICENSE" in
   bsd-go)
     LICENSE_TYPE=BSD3_THE_GO_AUTHORS
     ;;
-  mit|mit-project)
+  mit | mit-project)
     LICENSE_TYPE=MIT_PROJECT
     ;;
   mit-owner)
     LICENSE_TYPE=MIT_OWNER
     ;;
-  apache)
-    LICENSE_TYPE=Apache
+  apache2)
+    LICENSE_TYPE=Apache2
     ;;
-  mercari|merpay)
+  mercari)
     LICENSE_TYPE=
     ;;
   *)
@@ -69,18 +73,15 @@ if [[ -d '.git' ]]; then
 fi
 git init > /dev/null 2>&1
 
-# remove LICENSE file if exist
-if [[ -f 'LICENSE' ]]; then
-  rm -f LICENSE
-fi
-
-# write LICENSE
-if [[ -n "$LICENSE_TYPE" ]]; then
-  cat "$XDG_CONFIG_HOME/license/$LICENSE_TYPE" > LICENSE
-  if [[ "$LICENSE_TYPE" == "BSD3_PROJECT" ]] || [[ "$LICENSE_TYPE" == "MIT_PROJECT" ]]; then
-    sed -i "s|\$PROJECT_NAME|$PROJECT_NAME|g" LICENSE
+# write LICENSE if not exist
+if [[ ! -f 'LICENSE' ]]; then
+  if [[ -n "$LICENSE_TYPE" ]]; then
+    cat "$XDG_CONFIG_HOME/license/$LICENSE_TYPE" > LICENSE
+    if [[ "$LICENSE_TYPE" == "BSD3_PROJECT" ]] || [[ "$LICENSE_TYPE" == "MIT_PROJECT" ]]; then
+      sed -i "s|\$PROJECT_NAME|$PROJECT_NAME|g" LICENSE
+    fi
+    sed -i "s|\$YEAR|$(date '+%Y')|g" LICENSE
   fi
-  sed -i "s|\$YEAR|$(date '+%Y')|g" LICENSE
 fi
 
 pushd "$GIIGNORE_REPOSITORY" > /dev/null 2>&1
@@ -88,7 +89,7 @@ git pull origin master > /dev/null 2>&1
 popd > /dev/null 2>&1
 
 # write .gitignore
-cat <<EOF > .gitignore
+cat << EOF > .gitignore
 # $PROJECT_NAME project generated files to ignore
 #  if you want to ignore files created by your editor/tools,
 #  please consider a global .gitignore https://help.github.com/articles/ignoring-files
@@ -97,10 +98,9 @@ EOF
 
 # write .gitattributes
 touch .gitattributes
-cat <<EOF >> .gitattributes
+cat << EOF >> .gitattributes
 # $PROJECT_NAME project gitattributes file
-#  https://github.com/github/linguist#using-gitattributes
-#  https://github.com/github/linguist/blob/master/lib/linguist/languages.yml
+#  https://github.com/github/linguist/blob/master/docs/overrides.md
 
 # To prevent CRLF breakages on Windows for fragile files, like testdata.
 * -text
@@ -108,10 +108,10 @@ cat <<EOF >> .gitattributes
 docs        linguist-documentation
 EOF
 
-EXISTS=true
-for lang in ${ARG_LANGUAGES[*]}; do
+declare EXISTS=true
+for lang in "${ARG_LANGUAGES[@]}"; do
   LANGUAGE_IGNORE_FILE="${lang}.gitignore"
-  if [[ $lang == 'go-pkg' ]] || [[ $lang == 'go-simple' ]] ; then
+  if [[ $lang == 'go-pkg' ]] || [[ $lang == 'go-simple' ]]; then
     LANGUAGE_IGNORE_FILE="Go.gitignore"
   fi
   if [[ ! -f "$GIIGNORE_REPOSITORY/$LANGUAGE_IGNORE_FILE" ]]; then
@@ -133,11 +133,11 @@ for lang in ${ARG_LANGUAGES[*]}; do
   fi
 
   case "$lang" in
-    go|go-pkg|go-simple|Go|Go-pkg)
+    go | go-old)
       sed -i 's|# vendor/|vendor/|' .gitignore
 
       {
-      echo "
+        echo "
 # Compiled Object files, Static and Dynamic libs (Shared Objects)
 *.o
 *.a
@@ -173,26 +173,42 @@ coverage.*"
       } >> .gitignore
 
       # write .gitattributes
-      cat <<EOF >> .gitattributes
+      cat << EOF >> .gitattributes
 *.pb.go     linguist-generated
 *gen.go     linguist-generated
 *_string.go linguist-generated
 EOF
 
       # golangci-lint
-      cp "$XDG_DATA_HOME/boilerplate/go/.golangci.yml" .
+      cp "$XDG_CONFIG_HOME/boilerplate/go/.golangci.yml" .
       sed -i "s|# local-prefixes: github.com/|local-prefixes: github.com/$ORGANIZATION_NAME/$PROJECT_NAME|" .golangci.yml
+      sed -i "s|\$AUTHOR|$PROJECT_NAME|" .golangci.yml
 
       # creates hack directory
       mkdir -p hack/boilerplate
-      cp "$XDG_DATA_HOME/boilerplate/go/boilerplate.go.txt" hack/boilerplate
+      cp "$XDG_CONFIG_HOME/boilerplate/go/boilerplate.go.txt" hack/boilerplate
       sed -i "s|PKG|$PROJECT_NAME|g" hack/boilerplate/boilerplate.*.txt
       sed -i "s|YEAR|$(date +%Y)|g" hack/boilerplate/boilerplate.*.txt
 
-      if [[ "$lang" != "go-simple" ]]; then
+      # create root go.mod
+      go mod init && go mod edit -go=1.17
+
+      # create tools directory
+      mkdir -p tools
+      pushd tools > /dev/null 2>&1
+      go mod init && go mod edit -go=1.17
+      cat "$XDG_CONFIG_HOME/boilerplate/go/boilerplate.go.tools.txt" > tools.go
+      sed -i "s|PKG|$PROJECT_NAME|g" tools.go
+      sed -i "s|YEAR|$(date +%Y)|g" tools.go
+      go mod edit -require=golang.org/x/tools@master
+      go mod tidy -v
+      popd > /dev/null 2>&1
+
+      # write Makefile
+      if [[ "$lang" != "go" ]]; then
         mkdir -p hack/make
-        cp "$XDG_DATA_HOME/boilerplate/go/go.mk" hack/make/go.mk
-        cat <<EOF >> Makefile
+        cp "$XDG_CONFIG_HOME/boilerplate/go/go.mk" hack/make/go.mk
+        cat << EOF >> Makefile
 # ----------------------------------------------------------------------------
 # global
 
@@ -212,12 +228,8 @@ include hack/make/go.mk
 # ----------------------------------------------------------------------------
 # overlays
 EOF
-      if [[ "$lang" == *"go-simple"* ]]; then
-        cp "$XDG_DATA_HOME/boilerplate/go/go-pkg.mk" hack/make/go.mk
       fi
-
-      fi
-    ;;
+      ;;
 
     orb)
       NAMESPACE=$ORGANIZATION_NAME
@@ -228,11 +240,11 @@ EOF
       sed -i "s|$PROJECT_NAME|$ORGANIZATION_NAME/$PROJECT_NAME|" .gitignore
       sed -i "s|$PROJECT_NAME|$ORGANIZATION_NAME/$PROJECT_NAME|" .gitattributes
       mkdir -p src hack/boilerplate hack/make
-      cp "$XDG_DATA_HOME"/boilerplate/yaml/orb/boilerplate.*.txt hack/boilerplate/
-      cp "$XDG_DATA_HOME/boilerplate/yaml/orb/.yamllint" .yamllint
-      cp "$XDG_DATA_HOME/boilerplate/yaml/orb/orb.mk" hack/make/
+      cp "$XDG_CONFIG_HOME"/boilerplate/yaml/orb/boilerplate.*.txt hack/boilerplate/
+      cp "$XDG_CONFIG_HOME/boilerplate/yaml/orb/.yamllint" .yamllint
+      cp "$XDG_CONFIG_HOME/boilerplate/yaml/orb/orb.mk" hack/make/
       sed -i "s|PKG|$PROJECT_NAME|g" hack/boilerplate/boilerplate.*.txt
-      cat <<EOF >> src/orb.yml
+      cat << EOF >> src/orb.yml
 
 version: 2.1
 
@@ -240,7 +252,7 @@ description: |
 
 EOF
 
-      cat <<EOF >> Makefile
+      cat << EOF >> Makefile
 # ----------------------------------------------------------------------------
 # global
 
@@ -262,47 +274,41 @@ include hack/make/orb.mk
 EOF
 
       {
-      echo "
+        echo "
 # packed orb
 /src/$PROJECT_NAME.yml"
       } >> .gitignore
-    ;;
+      ;;
 
     *)
       mkdir -p hack/boilerplate
       {
-        if find "$XDG_DATA_HOME/boilerplate/$lang" -maxdepth 1 -type f -name 'boilerplate.*.txt' > /dev/null 2>&1; then
-          cp "$XDG_DATA_HOME"/boilerplate/"$lang"/boilerplate.*.txt hack/boilerplate/
+        if find "$XDG_CONFIG_HOME/boilerplate/$lang" -maxdepth 1 -type f -name 'boilerplate.*.txt' > /dev/null 2>&1; then
+          cp "$XDG_CONFIG_HOME/boilerplate/$lang"/boilerplate.*.txt hack/boilerplate/
           sed -i "s|PKG|$PROJECT_NAME|g" hack/boilerplate/boilerplate.*.txt
         fi
       }
-    ;;
+      ;;
   esac
 done
 
 # creates README.md
-printf "%s\\n" "# $PROJECT_NAME" > README.md
+printf "#%s\\n" "$PROJECT_NAME" > README.md
 
 # set git remote origin
 git remote add origin "git@github.com:$ORGANIZATION_NAME/$PROJECT_NAME.git" > /dev/null 2>&1 || true
 
 # git add
-if [[ -f .gitignore ]]; then
-  git add .gitignore
-fi
-if [[ -f .gitattributes ]]; then
-  git add .gitattributes
-fi
-if [[ -f LICENSE ]]; then
-  git add LICENSE
-fi
-
-if [[ "x$lang" == "xgo-simple" ]]; then
-  git add hack/boilerplate
-fi
-
+[[ -f .gitignore ]]      && git add .gitignore
+[[ -f .gitattributes ]]  && git add .gitattributes
+[[ -f LICENSE ]]         && git add LICENSE
 
 # git commit
-git commit -m 'Initial commit' --gpg-sign > /dev/null 2>&1
+git commit -m 'Initial commit' --signoff --gpg-sign > /dev/null 2>&1
+
+# if [[ -f go.mod ]]; then
+#   git add go.mod
+#   git commit -m 'module: init Go module' --signoff --gpg-sign > /dev/null 2>&1
+# fi
 
 info "Generated $PROJECT_NAME repository"
