bin/update-gcloud: update gcloud components

diff --git a/bin/update-gcloud b/bin/update-gcloud
--- a/bin/update-gcloud
+++ b/bin/update-gcloud
@@ -1,23 +1,37 @@
 #!/usr/bin/env bash
 set -euo pipefail
+# shellcheck shell=bash
 
 BIN="${0##*-}"
 
-info() { printf "\\x1b[1;34m[INFO]\\x1b[0m %s\\n\\n" "$1"; }
-error() { printf "\\x1b[1;31m[ERROR]\\x1b[0m %s\\n\\n" "$1"; }
+function info() { printf "\\x1b[1;34m[INFO]\\x1b[0m %s\\n\\n" "$1"; }
+# shellcheck disable=SC2329
+function error() { printf "\\x1b[1;34m[ERROR]\\x1b[0m %s\\n\\n" "$1" >&2; }
 
-[[ ! $# -eq 1 ]] && { echo "[ERROR] Usage: $BIN [VERSION]"; exit 1; }
+[[ ! $# -eq 1 ]] && {
+  echo "[ERROR] Usage: $BIN [VERSION]"
+  exit 1
+}
 VERSION=$1
 
-OS=$(uname | tr '[:upper:]' '[:lower:]')
+OS=$(uname -s | tr '[:upper:]' '[:lower:]')
+ARCH=$(uname -m | sed -E 's|(arm)64|\1|')
 
-_restore_sdk() {
-  cp -r /tmp/google-cloud-sdk "$CLOUDSDK_ROOT_DIR"
-  rm -rf /tmp/google-cloud-sdk
+function _restore_properties() {
+  if [[ -f '/tmp/properties' ]]; then
+    info "Restore google-cloud-sdk/properties ..."
+    cp /tmp/properties "${CLOUDSDK_ROOT_DIR}"
+  fi
 }
 
 # Take care of signals
-_trap_exit() { # Handle trapped signals
+# shellcheck disable=SC2329
+function _trap_exit() { # Handle trapped signals
+  function _restore_sdk() {
+    cp -R /tmp/google-cloud-sdk "$CLOUDSDK_ROOT_DIR"
+    rm -rf /tmp/google-cloud-sdk
+  }
+
   case $1 in
     INT)
       error "interrupted by user"
@@ -42,63 +56,89 @@ trap "_trap_exit INT" INT
 trap "_trap_exit TERM" TERM HUP
 
 if [[ -f "$CLOUDSDK_ROOT_DIR/properties" ]]; then
+  # shellcheck disable=SC2218
   info "Backup google-cloud-sdk/properties..."
   mv "$CLOUDSDK_ROOT_DIR/properties" /tmp
 
+  # shellcheck disable=SC2218
   info "Backup old google-cloud-sdk..."
   mv "$CLOUDSDK_ROOT_DIR" /tmp
 fi
 
+install_path=
+case $(uname -m) in
+  x86_64)
+    install_path='/usr/local'
+    ;;
 
-info "Install google-cloud-sdk $VERSION for $OS..."
-curl -sSL https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-"$VERSION"-"$OS"-x86_64.tar.gz | tar -C /usr/local -xzf -
+  arm64)
+    install_path='/opt/local'
+    ;;
+esac
+
+info "Install google-cloud-sdk ${VERSION} for ${OS} ${ARCH}..."
+curl -sSL "https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-${VERSION}-${OS}-${ARCH}.tar.gz" | tar -C "${install_path}" -xzf -
 
 info "Install gcloud components..."
-/usr/local/google-cloud-sdk/install.sh --usage-reporting=false --command-completion=false --path-update=false --install-python=true --quiet --additional-components \
+"${install_path}/google-cloud-sdk/install.sh" --usage-reporting=false --command-completion=false --path-update=false --install-python=true --quiet --additional-components \
   alpha \
-  app-engine-go \
-  app-engine-java \
-  app-engine-python \
-  app-engine-python-extras \
   beta \
   bq \
-  cloud-run-proxy \
-  cloud_sql_proxy \
+  bundled-python3-unix \
   config-connector \
   core \
   docker-credential-gcr \
+  gcloud-crc32c \
+  gcloud-deps \
   gcloud-man-pages \
+  gke-gcloud-auth-plugin \
   gsutil \
-  kpt \
+  istioctl \
   kubectl \
   kubectl-oidc \
-  kustomize \
-  local-extract \
-  minikube \
-  nomos \
+  log-streaming \
   package-go-module \
   pkg \
-  pubsub-emulator \
-  skaffold \
-  terraform-tools
-  # cloud-build-local \
-  # terraform-validator
-  # anthos-auth  \
+  preview \
+  run-compose \
+  spanner-cli \
+  terraform-tools \
+  universal-maker
+
+  # app-engine-go \
+  # app-engine-grpc \
+  # app-engine-java \
   # app-engine-php \
-  # appctl \
+  # app-engine-python \
+  # app-engine-python-extras \
   # bigtable \
-  # cbt  \
-  # cloud-datastore-emulator  \
+  # cbt \
+  # cloud-datastore-emulator \
   # cloud-firestore-emulator \
+  # cloud-run-proxy \
+  # cloud_sql_proxy \
+  # dataflow-sql \
   # datalab \
   # emulator-reverse-proxy \
+  # harbourbridge \
+  # hidden \
+  # kpt \
+  # kustomize \
+  # local-extract \
+  # minikube \
+  # nomos \
+  # pubsub-emulator \
+  # skaffold \
+  # terraform-validator \
+  # tests \
 
-if [[ -f '/tmp/properties' ]]; then
-  info "Restore google-cloud-sdk/properties"
-  cp /tmp/properties "$CLOUDSDK_ROOT_DIR"
-fi
+  _restore_properties
 
 rm -rf /tmp/google-cloud-sdk
 
 info "Successful Install Google Cloud SDK"
+
+info "Generate gcloud zsh completion"
+register-python-argcomplete -s zsh gcloud | tee ~/.config/zsh/completions/_gcloud > /dev/null 2>&1
+
 exit 0
